import type { Metadata } from "next";
import { Anton, Inter } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/layout/AppLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const anton = Anton({
  weight: "400",
  variable: "--font-heading",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"], // ✅ Add fallback
  adjustFontFallback: true, // ✅ Reduce layout shift
});

const inter = Inter({
  weight: ["400", "500", "600"],
  variable: "--font-body",
  subsets: ["latin"],
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"], // ✅ Add fallback
  adjustFontFallback: true, // ✅ Reduce layout shift
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "https://your-domain.com",
  ),

  title: "Merch Sports",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "TypeScript"],
  referrer: "origin-when-cross-origin",
  category: "technology",

  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: "/icon0.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180" }],
  },

  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anton.variable} ${inter.variable} antialiased`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
